sudo: false
language:
- java
- node_js
node_js:
- '7'
jdk:
- oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "junkerm-github"
    token:
      secure: ouSVaXsI0TG9k+vu+jF3bY3zqdFyDN5dCeWNZvq/RfBVzlibdWDF/RKX6/yx/SUmzxqt+NZ8/fXTXRkyOjwbRAimCmnjahO+UusFm9RwvKA4AxzzgSMebglaq2213Gb+apnsQHZrclyFsEpKWAklduRNqAlV2E4tE9IcLtNDDyKL3hooYsf6zlPzsrvqiBx8Fyh798SuyxA92DFn9BDZTd6AyItoXx4wYwnWC3mbtBA2yTjbwN9VuZ0Z3vvvT0F6oC68v3SBLTXur3I4jBAFQgncj50ylX/tw+u6ED5KW5LMhMrwmCDJgpB/34v7KdJFGZHBaiHylDkl5t6zV2k4ETNbRZUYUUzte2NkYvlqrFu482WleNgjdB1xBLqLwRNK8ZykwKLK0npt2Sv6DCTGcv2I3J5GBSX57SadPUyl4ACKjJFWe6jznMdGgJ9zqXXm+cN8lv8Aucx0pM2wuVzuLiNb19oYv+Lb1KWGujGn3Ck3jsto62RCetFANXkrTjcg2y/m0e+6fyWAwLJnVjnxN/cekEv5KkG5i+LZEaO2xUnQQ4mXKUFQHJGRl1gD6Wz4O84+4lH51PQIUUgS9PwPAOHxtMNoumhTqVJU3UtzBtXQ0hI9qUk2+cM4/iuNL7ItgJysWOQlyb5pzoQ73bqdCljBLtsmhNYY1Q7WRyclJJo=
env:
- TERM=dumb
install:
- cd web && npm run init
- cd ../bundles && ./gradlew --version
script:
- sonar-scanner -X -Dsonar.projectVersion=0.2.5
- cd ../web && npm run build-prod
- cd ../bundles && ./gradlew build --continue
- cd ../bundles && ./gradlew check
- cd ../bundles && ./gradlew export
- cd ..
after_success:
- git status
cache:
  directories:
  - cnf/cache/stable
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eUiVeNw9rlpcaXi+bpoV4B4WFEjXCgBn6td9NRXFF9dOcJiozn5oHh6qk8g6kMHuUrGDCKcOo5fitxkNaoV1vqxNuRjo7ssPN3yG3QcUmIlsMHM2ueM+9AEyQxP1SuNXku/Vb+ATQ1F7jWUlWotcCWTPbELuhUvziwcF4zYWm2jcTL1twD3gCT9GFdovqnUnmVLHrUha4EUO8bwFlJmyaSmxH5RpcTbKK2tRagRlv/4yUajhBxaNgCXD2nBpNtV6nb2sPbybilB9gRO5d4oPurNQWb28aiobGm0+hNU5bG+MYOyF3fJWU7NaQ0tQP0M8zZ5QM/Lw8g/xMOdMaqZ2rHWPNyxFqNFsUa+H1S9f+tEmje+kvTZ7oPZRuzy90dYC1ZzwpuhG9y3qIlpnDs+9E+JRU3yASEWeb7VVZFrMJKK3wh/FEvVCduYKoTYgcckFeipkjQY1V/umfKRrlq/3ZFATBX3PKaUnHzctZ+KK2nEWBiYMLacw8JKqQSjTIGRchjLZHYpuTR2CuttfBHVH1kDs0SNd7mKsFQShzXfPDylHTT0ZyfVJ++IKaf1Ww37dmqui0FTULmVTy1vtmkcImpFX0y9WFWoOy1vI7QWM4U3YfasRBZlIigNNyLgPR3Bzg+Z+6YBVUdi4T/ulsDf7iU7ZEOD5g7fl06gfcDAKr9E=
  file: 
    - bundles/specmate-std-env/generated/distributions/executable/dev-specmate-all.jar
    - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-all.jar
    - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-cdo-server.jar
    - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-no-cdo-server.jar
  on:
    repo: junkerm/specmate
    branch: master
    tags: true
