sudo: false
language:
- java
- node_js
node_js:
- '7'
jdk:
- oraclejdk8
addons:
  sauce_connect: true
env:
  global:
  - TERM=dumb
  - secure: B8Dip2FKho+Ub2S3sEVZeAi5qudntPuEtD38nGfUwMK907mYeucM1iiMlhoiuU1f1PJ/2C/GY4318zLX1AjTxuQ807gs3s/pjS87PBpxbJYoW1udq3dTnr00ecrEF1r1OETe+ABG4ojHAvC/HxaGlPsqluWPvtGcFZt1XJ8nocQFOi5Ya9CSPT9YRwlkgd/Zjg3rNud2DblCKO9/dgNuPu06wwfbIUU9dj7jb/jRdiTP1oPvxnIGjA2htcpUUhRK3eoGcXkOQ/fuF4ANlySLZ3lOqZ/VMKA0J66R61pNfcqSjcHQoLoeEjHGkf1+/LAnGJWLv6oPirRQ9CfJL0LRdfEvAjcNtsd+g/gBj0lGk31Z9ObbesS3dShkF0shLs+Q+pn53qN4UuXbhOd2OgxZ0gRwBEDO8ra8eUD0Pko7KvJEeysr8UqXPGhvVMUVuChTEClyNsCkuVq5iUYUVmudHkGd3hjOD+m9S7XyvAOUCji8nrLGKdJ13nWgXCSmslTWS5k54wGHicd3qnKLmepAVp0WC3eUieGS0bXOh/gKKddeP8yFr25bXuXrNU8Bp04+7SZpfgWocvs4d7QsBmwjxlrbll9HLpaXIIjlHL89fsO/Ye6VlEogPDw7q6EBiH/I+IuT1mJZFlfyupcvBn1x3XHVki+x7AA05X6ryDk+OlU=
  - secure: IQAe+tnVELZFxoi1uOaZ4RHUjulRQUWEt/S9LYE2phgS/szvhFaTZR9fpPfxnHhwlW4jVNH2PA9E55HLJNwn62+Z0oarcuY+jvUII2dJQybzDA4kG/uA4XC2r0UdNlNjfj/qVM7IT6/y6AtZI+/5bB8QoGRDpN7BlahOeY1Mi3RyTrqYBHX5pJT7vggnpOs9yf6ejBBMBAL05aEwDyvBak/YTEmjT1wV6ZAlFwjpR95rHE++hNsu1nAyePUwdYDD+XqfMZEkcYjxMeQL0zO2Bt42RvSOR7nZTS/P0+tWYglGHa32E9E/nTzxhUAbe37hmExNSCiInDyNE25exOAusWeqLZ5yd/Bj56wHp0Zt2C18SC/cL5x6RmxxmM4tMHtA5Q9j8wgQm41yb1OXDwIbuquxKwLSxvVqHM6bl6nZpWj+chNBkLbn3aRQDUBG5uJJIhdzvO0RaRYEitydbsXxoQu00U2w8UihdeWHd/QFjw41mUPzjQLH70e75G4H1p4bQ7OI1zi5OmNTC5uQ6B8h7sU7L9dvPynGBHEYl0NaM63NPuLjLJwP01FqTP+PZGWjB4LcqN/74v22XtkFcRa1Cg/oQD4JCicLPCLVN5qxbEqdpmgkB6r+inzuAn/J5RNaE+h/mgK6CasVLzVfyVo2SW0fSoJzqC4jIqGVkvRudv8=

install:
- cd web && npm run init
- cd ../bundles && ./gradlew --version
script:
- cd ../web && npm run build-prod
- cd ../bundles && ./gradlew build --continue
- cd ../bundles && ./gradlew check
- cd ../bundles && ./gradlew export
- cd ..
- cd specmate-ui-tests-master/src/SpecmateTestClasses/ && javac UC3ModelCEG.java
after_success:
- git status
cache:
  directories:
  - cnf/cache/stable
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: eUiVeNw9rlpcaXi+bpoV4B4WFEjXCgBn6td9NRXFF9dOcJiozn5oHh6qk8g6kMHuUrGDCKcOo5fitxkNaoV1vqxNuRjo7ssPN3yG3QcUmIlsMHM2ueM+9AEyQxP1SuNXku/Vb+ATQ1F7jWUlWotcCWTPbELuhUvziwcF4zYWm2jcTL1twD3gCT9GFdovqnUnmVLHrUha4EUO8bwFlJmyaSmxH5RpcTbKK2tRagRlv/4yUajhBxaNgCXD2nBpNtV6nb2sPbybilB9gRO5d4oPurNQWb28aiobGm0+hNU5bG+MYOyF3fJWU7NaQ0tQP0M8zZ5QM/Lw8g/xMOdMaqZ2rHWPNyxFqNFsUa+H1S9f+tEmje+kvTZ7oPZRuzy90dYC1ZzwpuhG9y3qIlpnDs+9E+JRU3yASEWeb7VVZFrMJKK3wh/FEvVCduYKoTYgcckFeipkjQY1V/umfKRrlq/3ZFATBX3PKaUnHzctZ+KK2nEWBiYMLacw8JKqQSjTIGRchjLZHYpuTR2CuttfBHVH1kDs0SNd7mKsFQShzXfPDylHTT0ZyfVJ++IKaf1Ww37dmqui0FTULmVTy1vtmkcImpFX0y9WFWoOy1vI7QWM4U3YfasRBZlIigNNyLgPR3Bzg+Z+6YBVUdi4T/ulsDf7iU7ZEOD5g7fl06gfcDAKr9E=
  file:
  - bundles/specmate-std-env/generated/distributions/executable/dev-specmate-all.jar
  - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-all.jar
  - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-cdo-server.jar
  - bundles/specmate-std-env/generated/distributions/executable/prod-specmate-no-cdo-server.jar
  on:
    repo: junkerm/specmate
    branch: master
    tags: true
